"""check

Revision ID: d3cec2690b6b
Revises: 
Create Date: 2023-03-11 14:22:00.002535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3cec2690b6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schoolcelebration',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Schoolcelebration', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('schoolprogramme',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('SchoolProgramme', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('studentprogramme',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('StudentProgramme', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('users',
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(length=50), nullable=False),
    sa.Column('Password', sa.String(length=50), nullable=False),
    sa.Column('OTP', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('UserId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('studentprogramme')
    op.drop_table('schoolprogramme')
    op.drop_table('schoolcelebration')
    # ### end Alembic commands ###
